//! ReactiveChildren — a layout container whose children are (re)generated by
//! an app-supplied builder whenever a reactive dependency changes.
//!
//! This is the framework's "reactive children" primitive: the only other way
//! to rebuild a subtree is [`EventContext::rebuild_children`](crate::EventContext),
//! which must be triggered by hand from an event handler. A `ReactiveChildren`
//! instead re-runs its builder automatically — the tree checks a cheap version
//! token once per layout pass (see
//! [`WidgetTree::sync_reactive_children`](crate::tree::WidgetTree)) and, when
//! the token differs from the last build, tombstones the current children and
//! re-runs the builder before laying out.
//!
//! The widget is deliberately content-agnostic: it knows nothing about what it
//! renders. Knot uses it to drive a live markdown preview off the note body
//! (`version = hash(body)`, `build = preview::render(...)`), keeping the
//! markdown mapping entirely app-side.
//!
//! ## Version token
//!
//! `version` is an app-supplied `Fn() -> u64`. The app is responsible for
//! returning a value that changes if and only if the content the builder
//! depends on changed — e.g. a hash of the source string, or a monotonic
//! revision counter. The token is compared against the previous build's token,
//! so it only needs to be stable within a single process run. A cheap, always-
//! correct choice is to hash the source each pass (the compare is the only
//! per-frame cost; the rebuild fires only on a real change).

use std::cell::{Cell, RefCell};

use crate::paint::PaintContext;
use crate::tree::WidgetTree;
use crate::widget::Widget;
use shroud_core::Rect;
use shroud_layout::FlexStyle;

/// Returns the current change token for a [`ReactiveChildren`]. Called once per
/// layout pass; the children rebuild whenever its result differs from the last
/// build's.
type VersionFn = Box<dyn Fn() -> u64>;

/// Populates a [`ReactiveChildren`]'s children. Receives the tree and the
/// (stable) index of the `ReactiveChildren` node so it can
/// `tree.add_child(parent, ...)`. `FnMut` because it runs again on every
/// version change.
type BuildFn = Box<dyn FnMut(&mut WidgetTree, usize)>;

/// A layout container that rebuilds its children when a version token changes.
///
/// Construct with [`ReactiveChildren::column`] / [`ReactiveChildren::row`],
/// chain layout builders (`width_full`, `gap`, `grow`, `flex_basis`, …), then
/// attach the reactive source with [`ReactiveChildren::source`]. The widget
/// paints nothing of its own — it is purely a flex box whose contents track a
/// dependency.
pub struct ReactiveChildren {
    style: FlexStyle,
    /// Change token. Defaults to a constant `0` until [`Self::source`] sets it;
    /// a `ReactiveChildren` with no source simply never builds.
    version: VersionFn,
    /// The child builder, held in an `Option` so the tree can take it out to
    /// call it (`build(&mut tree, idx)` needs `&mut WidgetTree`, which can't
    /// coexist with a borrow into the node) and put it back afterward. `RefCell`
    /// gives that take/replace through the `&self` the downcast yields.
    build: RefCell<Option<BuildFn>>,
    /// Token of the most recent build, or `None` before the first build. `Cell`
    /// so the sync pass can update it through `&self`.
    last_version: Cell<Option<u64>>,
}

impl ReactiveChildren {
    /// Create a column container (vertical stacking).
    pub fn column() -> Self {
        Self::with_style(FlexStyle::new().column())
    }

    /// Create a row container (horizontal stacking).
    pub fn row() -> Self {
        Self::with_style(FlexStyle::new().row())
    }

    fn with_style(style: FlexStyle) -> Self {
        Self {
            style,
            version: Box::new(|| 0),
            build: RefCell::new(None),
            last_version: Cell::new(None),
        }
    }

    /// Attach the reactive source.
    ///
    /// `version` is read once per layout pass; whenever its result differs from
    /// the previous build, `build` re-runs to repopulate the children. `build`
    /// receives the tree and this node's stable index — call
    /// `tree.add_child(parent, ...)` to add children, exactly as in a
    /// [`EventContext::rebuild_children`](crate::EventContext) closure.
    pub fn source<V, B>(mut self, version: V, build: B) -> Self
    where
        V: Fn() -> u64 + 'static,
        B: FnMut(&mut WidgetTree, usize) + 'static,
    {
        self.version = Box::new(version);
        self.build = RefCell::new(Some(Box::new(build)));
        self
    }

    /// Set gap between children.
    pub fn gap(mut self, px: f32) -> Self {
        self.style = self.style.gap(px);
        self
    }

    /// Set padding on all sides.
    pub fn padding(mut self, px: f32) -> Self {
        self.style = self.style.padding(px);
        self
    }

    /// Fill available width.
    pub fn width_full(mut self) -> Self {
        self.style = self.style.width_full();
        self
    }

    /// Fill available height.
    pub fn height_full(mut self) -> Self {
        self.style = self.style.height_full();
        self
    }

    /// Grow to fill available space.
    pub fn grow(mut self, factor: f32) -> Self {
        self.style = self.style.grow(factor);
        self
    }

    /// Set the initial main-axis size (`flex-basis`) in pixels. See
    /// [`FlexStyle::flex_basis`].
    pub fn flex_basis(mut self, px: f32) -> Self {
        self.style = self.style.flex_basis(px);
        self
    }

    // ── Tree-facing internals (crate-private) ───────────────────────────────

    /// Current change token.
    pub(crate) fn version(&self) -> u64 {
        (self.version)()
    }

    /// The token of the most recent build, or `None` before the first build.
    pub(crate) fn last_version(&self) -> Option<u64> {
        self.last_version.get()
    }

    /// Record the token the children were just (re)built at.
    pub(crate) fn set_last_version(&self, v: u64) {
        self.last_version.set(Some(v));
    }

    /// Take the builder out so the tree can call it with `&mut WidgetTree`.
    /// Returns `None` for a source-less node, or if a reentrant rebuild already
    /// has it out.
    pub(crate) fn take_builder(&self) -> Option<BuildFn> {
        self.build.borrow_mut().take()
    }

    /// Return the builder after a rebuild.
    pub(crate) fn restore_builder(&self, build: BuildFn) {
        *self.build.borrow_mut() = Some(build);
    }
}

impl Widget for ReactiveChildren {
    fn style(&self) -> FlexStyle {
        self.style.clone()
    }

    /// Pure layout box — nothing of its own to draw. Children are painted by
    /// the tree.
    fn paint(&self, _layout: Rect, _ctx: &mut PaintContext) {}
}
